# Generated by Django 5.2.8 on 2025-12-07 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pgn", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analyzed", models.BooleanField(default=False)),
                ("result", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "white_player",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "black_player",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("event", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
