# Generated by Django 5.2.8 on 2025-12-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.IntegerField()),
                ("san", models.CharField(max_length=20)),
                ("evaluation", models.FloatField(null=True)),
                ("best_move", models.CharField(max_length=20, null=True)),
                ("centipawn_loss", models.FloatField(null=True)),
                ("classification", models.CharField(max_length=20, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="analysis.game",
                    ),
                ),
            ],
        ),
    ]
