# Generated by Django 5.2.8 on 2025-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_move"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Move",
        ),
    ]
