# Generated by Django 5.2.8 on 2025-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="accuracy",
            field=models.FloatField(null=True),
        ),
    ]
