# Generated by Django 5.2.8 on 2025-12-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_game_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="avg_cp_loss",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="max_advantage",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="min_advantage",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="num_best",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_blunder",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_brilliant",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_excellent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_good",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_great",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_inaccuracy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="num_mistake",
            field=models.IntegerField(default=0),
        ),
    ]
