# Generated by Django 5.2.8 on 2025-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0006_game_avg_cp_loss_game_max_advantage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="accuracy",
            new_name="black_accuracy",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_best",
            new_name="black_num_best",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_blunder",
            new_name="black_num_blunder",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_brilliant",
            new_name="black_num_brilliant",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_excellent",
            new_name="black_num_excellent",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_good",
            new_name="black_num_good",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_great",
            new_name="black_num_great",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_inaccuracy",
            new_name="black_num_inaccuracy",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="num_mistake",
            new_name="black_num_mistake",
        ),
        migrations.AddField(
            model_name="game",
            name="white_accuracy",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_best",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_blunder",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_brilliant",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_excellent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_good",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_great",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_inaccuracy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="white_num_mistake",
            field=models.IntegerField(default=0),
        ),
    ]
