# Generated by Django 5.2.8 on 2025-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0007_rename_accuracy_game_black_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="accuracy_score",
            field=models.FloatField(null=True),
        ),
    ]
