# Generated by Django 5.2.8 on 2025-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0008_move_accuracy_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="best_move_fen",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="move",
            name="neg_game_changing",
            field=models.BooleanField(default=False),
        ),
    ]
