# Generated by Django 5.2.8 on 2026-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0009_move_best_move_fen_move_neg_game_changing"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="san",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
